name: Deploy to production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: SSH Remote Pull
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo cd
            pwd
            cd discord/AutoRoll
            pwd
            echo compose down
            docker compose down
            echo pull
            git pull
            echo compose up
            docker compose up -d

