name: Deploy to production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: testVars
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TEST: ${{ secrets.TEST }}
        run: |
          echo username: 
          echo $USERNAME
          echo ${{ secrets.USERNAME }}
          echo test:
          echo $TEST
          echo ${{ secrets.TEST }}
          echo done
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            touch test
